trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - feature/*
      - main

pool: org_pool

variables:
  TF_VERSION: '1.6.6'
  TF_PLUGIN_CACHE_DIR: '$(Pipeline.Workspace)/tfplugin-cache'
  TF_LOG: ERROR

stages:

# =========================
# Terraform Tools & Scans
# =========================
- stage: Terraform_Quality
  displayName: Terraform Install & Scans
  jobs:

  - job: TerraformTools
    displayName: Terraform Tools & Security Scan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: PowerShell@2
      displayName: Create Plugin Cache
      inputs:
        targetType: inline
        script: |
          New-Item -ItemType Directory -Force -Path "$(TF_PLUGIN_CACHE_DIR)"

    - task: Cache@2
      inputs:
        key: terraform | "$(Agent.OS)"
        path: $(TF_PLUGIN_CACHE_DIR)

    - task: PowerShell@2
      displayName: TFLint
      inputs:
        targetType: inline
        script: |
          tflint --init
          tflint --format json > tflint-report.json

    - task: PowerShell@2
      displayName: Tfsec
      inputs:
        targetType: inline
        script: |
          tfsec . --format json > tfsec-report.json

    - task: PowerShell@2
      displayName: Checkov
      inputs:
        targetType: inline
        script: |
          checkov -d . --soft-fail -o json > checkov-report.json


# =========================
# Terraform Init & Plan
# =========================
- stage: Terraform_Plan
  displayName: Terraform Init & Plan
  dependsOn: Terraform_Quality
  jobs:

  - job: Plan
    displayName: Terraform Plan
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: Cache@2
      inputs:
        key: terraform | "$(Agent.OS)"
        path: $(TF_PLUGIN_CACHE_DIR)

    - task: PowerShell@2
      displayName: Terraform Init
      inputs:
        targetType: inline
        script: |
          terraform init `
            -backend-config="resource_group_name=praveen-rgs" `
            -backend-config="storage_account_name=praveen1234" `
            -backend-config="container_name=tfstate" `
            -backend-config="key=dev-terraform.tfstate"
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev

    - task: PowerShell@2
      displayName: Terraform Plan
      inputs:
        targetType: inline
        script: |
          terraform plan -no-color
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev


# =========================
# Manual Approval
# =========================
- stage: Manual_Validation
  displayName: Manual Validation
  dependsOn: Terraform_Plan
  pool: server
  jobs:
  - job: Approval
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'mishrapraveenm94@gmail.com'
        approvers: 'mishrapraveenm94@gmail.com'
        onTimeout: resume


# =========================
# Terraform Apply
# =========================
- stage: Terraform_Apply
  displayName: Terraform Apply
  dependsOn: Manual_Validation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:

  - job: Apply
    displayName: Terraform Apply
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: Cache@2
      inputs:
        key: terraform | "$(Agent.OS)"
        path: $(TF_PLUGIN_CACHE_DIR)

    - task: PowerShell@2
      displayName: Terraform Init
      inputs:
        targetType: inline
        script: |
          terraform init `
            -backend-config="resource_group_name=praveen-rgs" `
            -backend-config="storage_account_name=praveen1234" `
            -backend-config="container_name=tfstate" `
            -backend-config="key=dev-terraform.tfstate"
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev

    - task: PowerShell@2
      displayName: Terraform Apply
      inputs:
        targetType: inline
        script: |
          terraform apply -auto-approve
        workingDirectory: $(System.DefaultWorkingDirectory)/env/dev
