trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: terraformInitTest
    displayName: install and init
    jobs:
      - job: install_and_init
        displayName: install terraform and run init
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'


      - job: terraformLint
        displayName: Terraform Lint & Security


        steps:
        - checkout: self

        # tflint installation
        - script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          displayName: Install TFLint

        # run tflint
        - script: |
            cd code_practice/terrawork/azure/infra2/env/dev
            tflint --init
            tflint --format json | tee tflint-report.json
          displayName: Run TFLint

        # tfsec
        - script: |
            curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
            cd code_practice/terrawork/azure/infra2/env/dev

  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/code_practice/terrawork/azure/infra2/env/dev'
  #           backendServiceArm: 'azurecloud'
  #           backendAzureRmResourceGroupName: 'arpitRG'
  #           backendAzureRmStorageAccountName: 'arpit123'
  #           backendAzureRmContainerName: 'tfstate'
  #           backendAzureRmKey: 'dev-terraform.tfstate'
          
  # - stage: ManualValidation
  #   displayName: Manual Validation
  #   dependsOn: terraformInitTest
  #   pool: server

  #   jobs:
  #   - job: ManualValidation
  #     displayName: Manual Validation
  #     steps:
  #     - task: ManualValidation@1
  #       inputs:
  #         notifyUsers: |
  #           mishrapraveenm55@gmail.com
  #           arvishpanther@gmail.com
  #         approvers: 'arvishpanther@gmail.com'
  #         onTimeout: 'resume'

          